const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../dist/curriculum.js'),B=require('../dist/bank.js');
function mount(seed={}){const nodes=new Map(),listeners={},saved=new Map(Object.entries(seed));const get=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',value:'',style:{},classList:{toggle(){}},setAttribute(){},focus(){},addEventListener(){}});return nodes.get(id)};const context={console,Date,Math,JSON,Number,Set,Map,String,Array,Object,URLSearchParams,location:{hash:'#/home',search:'',origin:'http://localhost'},localStorage:{getItem:key=>saved.get(key)||null,setItem:(key,v)=>saved.set(key,v)},document:{getElementById:get,querySelectorAll:()=>[],documentElement:{},title:''},Curriculum:C,PhysicsBank:B,addEventListener:(name,fn)=>listeners[name]=fn,scrollTo(){}};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync('dist/shell.js','utf8'),context);return{context,nodes,saved,html:()=>get('app').innerHTML,route:hash=>{context.location.hash=hash;context.IyalApp.render(false)}}}
test('11 chapters and 72 unique bilingual lesson pages',()=>{assert.equal(C.chapters.length,11);assert.equal(C.total,72);const ids=C.chapters.flatMap(c=>c.lessons.map(l=>l.id));assert.equal(new Set(ids).size,72);assert.equal(C.chapters.flatMap(c=>c.lessons).filter(l=>l.available).length,1);for(const c of C.chapters){assert.ok(c.ta&&c.en&&c.source);for(const l of c.lessons)assert.equal(C.getLesson(c.id,l.slug),l)}});
test('all home, explorer, progress, practice, chapter and lesson routes render',()=>{const app=mount();for(const route of ['#/home','#/chapters','#/practice','#/progress',...C.chapters.flatMap(c=>['#/chapter/'+c.id,...c.lessons.map(l=>'#/chapter/'+c.id+'/'+l.slug)])]){app.route(route);assert.ok(!app.html().includes('undefined'),route);assert.ok(!app.html().includes('NaN'),route);assert.ok(app.html().includes('id="main"'),route);assert.notEqual(app.context.IyalApp.parse(route).type,'missing',route)}});
test('unbuilt lesson has four workspace sections and no false completion',()=>{const app=mount();app.route('#/chapter/01/measurement-missing');assert.equal(app.context.IyalApp.parse().type,'missing');app.route('#/chapter/01/dimensions');assert.ok(app.html().includes('role="tablist"'));assert.equal((app.html().match(/role="tab"/g)||[]).length,4);assert.ok(!app.html().includes('id="lesson-frame"'));assert.ok(app.html().includes('பாடம் உருவாக்கத்தில்'))});
test('existing practice evidence is reflected on home and progress',()=>{const history=Object.keys(B.families).flatMap(f=>[1,2].map(n=>({id:f+'-'+n,variant:0,at:Date.now(),correct:true,assisted:false})));const app=mount({'iyal-practice-v1':JSON.stringify(history),'iyal-language':'"en"'});assert.ok(app.html().includes('100%'));assert.ok(app.html().includes('Make space for another topic'));app.route('#/progress');assert.ok(app.html().includes('Ready for a new focus'));assert.ok(app.html().includes('1 subchapter assessed'))});
test('bookmarks persist without counting as learning progress',()=>{const app=mount({'iyal-language':'"en"'});app.route('#/chapter/01/vectors');app.nodes.get('save-lesson').onclick();assert.deepEqual(JSON.parse(app.saved.get('iyal-saved')),['01/vectors']);app.route('#/home');assert.ok(app.html().includes('Vectors'));assert.ok(app.html().includes('<strong>0<small> / 72'));app.route('#/chapter/01/vectors');app.nodes.get('save-lesson').onclick();assert.deepEqual(JSON.parse(app.saved.get('iyal-saved')),[])});
test('Tamil/English switch preserves route and writes preference',()=>{const app=mount();app.route('#/chapter/03');app.nodes.get('switch-language').onclick();assert.ok(app.html().includes('Oscillations &amp; waves'));assert.equal(app.context.location.hash,'#/chapter/03');assert.equal(app.saved.get('iyal-language'),'"en"')});
test('working lesson and practice retain old bank through same-origin embed',()=>{const app=mount();app.route('#/chapter/02/projectile');assert.ok(app.html().includes('lab.html?embed=1&lang=ta'));app.route('#/practice');assert.ok(app.html().includes('lab.html?embed=1&view=practice&lang=ta'))});
test('entrypoints include existing lesson and all referenced assets',()=>{for(const entry of ['index.html','lab.html']){const html=fs.readFileSync('dist/'+entry,'utf8');for(const match of html.matchAll(/(?:src|href)="([a-z-]+\.(?:js|css))"/g))assert.ok(fs.existsSync('dist/'+match[1]),match[1])}const lab=fs.readFileSync('dist/lab.html','utf8');assert.ok(lab.includes('id="scene"'));assert.ok(lab.includes('src="practice.js"'));assert.ok(lab.includes('src="lab-bridge.js"'))});
