# Generated by Django 5.2.17 on 2026-09-14 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ta', models.CharField(max_length=200)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ta', models.CharField(max_length=200)),
                ('position', models.PositiveSmallIntegerField()),
                ('available', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.chapter')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('style', models.CharField(max_length=60)),
                ('variant', models.PositiveSmallIntegerField()),
                ('family', models.CharField(max_length=60)),
                ('content', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('answer', models.CharField(blank=True, max_length=100)),
                ('correct', models.BooleanField(default=False)),
                ('assisted', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.question')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('lesson', 'style', 'variant'), name='unique_question_variant'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'question'], name='attempt_user_question'),
        ),
    ]
