# Generated by Django 5.2.17 on 2026-09-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier within this lesson, e.g. si-units.', max_length=80)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('theory', 'Explanation'), ('example', 'Worked example'), ('activity', 'Interactive activity'), ('check', 'Quick check')], default='theory', max_length=20)),
                ('published', models.BooleanField(default=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ta', models.CharField(max_length=200)),
                ('body_en', models.TextField(blank=True, help_text='Plain text. Blank lines separate paragraphs.')),
                ('body_ta', models.TextField(blank=True)),
                ('formula', models.CharField(blank=True, max_length=300)),
                ('activity', models.CharField(blank=True, choices=[('', 'None'), ('units', 'Unit converter'), ('vernier', 'Vernier calliper'), ('uncertainty', 'Repeated measurements'), ('vectors', 'Vector components')], max_length=30)),
                ('options_en', models.TextField(blank=True, help_text='For quick checks: one option per line, 2 to 5 options.')),
                ('options_ta', models.TextField(blank=True)),
                ('correct_option', models.PositiveSmallIntegerField(default=1, help_text='Correct option number, starting at 1.')),
                ('explanation_en', models.TextField(blank=True)),
                ('explanation_ta', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='learning.lesson')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'key'), name='unique_lesson_block')],
            },
        ),
    ]
