# Generated by Django 5.2.17 on 2026-09-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_publish_existing_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonblock',
            name='presentation',
            field=models.CharField(choices=[('plain', 'Paragraphs'), ('cards', 'Visual concept cards'), ('process', 'Investigation cycle'), ('approaches', 'Compare approaches'), ('branches', 'Physics branches')], default='plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='activity',
            field=models.CharField(blank=True, choices=[('', 'None'), ('units', 'Unit converter'), ('vernier', 'Vernier calliper'), ('uncertainty', 'Repeated measurements'), ('vectors', 'Vector components'), ('pendulum', 'Pendulum investigation'), ('particles', 'Ideal gas particles')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='body_en',
            field=models.TextField(blank=True, help_text='For visual layouts: separate cards with a blank line. Each card starts with a short heading, then a new line and its explanation.'),
        ),
    ]
