# Generated by Django 5.2.17 on 2026-09-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_lessonblock_presentation_alter_lessonblock_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='activity',
            field=models.CharField(blank=True, choices=[('', 'None'), ('units', 'Unit converter'), ('vernier', 'Vernier calliper'), ('uncertainty', 'Repeated measurements'), ('vectors', 'Vector components'), ('pendulum', 'Pendulum investigation'), ('particles', 'Ideal gas particles'), ('angles', 'Angle ratios')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='presentation',
            field=models.CharField(choices=[('plain', 'Paragraphs'), ('cards', 'Visual concept cards'), ('process', 'Investigation cycle'), ('approaches', 'Compare approaches'), ('branches', 'Physics branches'), ('table', 'Interactive reference table')], default='plain', max_length=20),
        ),
    ]
