# Generated by Django 5.2.17 on 2026-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_lessonblock_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='activity',
            field=models.CharField(blank=True, choices=[('', 'None'), ('units', 'Unit converter'), ('vernier', 'Vernier calliper'), ('uncertainty', 'Repeated measurements'), ('vectors', 'Vector components'), ('pendulum', 'Pendulum investigation'), ('particles', 'Ideal gas particles'), ('angles', 'Angle ratios'), ('dimension-builder', 'Dimension builder'), ('dimension-equations', 'Equation detective'), ('dimension-scaling', 'Pendulum scaling'), ('dimension-conversion', 'SI-CGS dimension converter')], max_length=30),
        ),
    ]
