# Generated by Django 5.2.17 on 2026-09-15 15:31

from django.db import migrations, models


def assign_vernier(apps, schema_editor):
    Block = apps.get_model('learning', 'LessonBlock')
    Block.objects.filter(lesson_id='01/instruments', key__startswith='caliper-', instrument='').update(instrument='vernier')


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_lessonblock_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonblock',
            name='instrument',
            field=models.CharField(blank=True, choices=[('', 'General lesson'), ('ruler', 'Metre rule'), ('vernier', 'Vernier caliper'), ('micrometer', 'Micrometer'), ('spherometer', 'Spherometer'), ('balance', 'Balance'), ('stopwatch', 'Stopwatch'), ('thermometer', 'Thermometer')], help_text='For Measuring Instruments: choose the instrument page where this block belongs.', max_length=30),
        ),
        migrations.RunPython(assign_vernier, migrations.RunPython.noop),
    ]
