# Generated by Django 5.2.17 on 2026-09-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_lessonblock_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='activity',
            field=models.CharField(blank=True, choices=[('', 'None'), ('units', 'Unit converter'), ('vernier', 'Vernier calliper'), ('uncertainty', 'Repeated measurements'), ('vectors', 'Vector components'), ('pendulum', 'Pendulum investigation'), ('particles', 'Ideal gas particles'), ('angles', 'Angle ratios'), ('dimension-builder', 'Dimension builder'), ('dimension-equations', 'Equation detective'), ('dimension-scaling', 'Pendulum scaling'), ('dimension-conversion', 'SI-CGS dimension converter'), ('error-target', 'Bias and scatter'), ('error-relative', 'Relative uncertainty'), ('error-propagation', 'Uncertainty propagation'), ('vernier-3d', '3D vernier caliper lab'), ('micrometer-3d', '3D micrometer lab'), ('spherometer-3d', '3D spherometer lab'), ('travelling-3d', '3D travelling microscope lab')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='instrument',
            field=models.CharField(blank=True, choices=[('', 'General lesson'), ('ruler', 'Metre rule'), ('vernier', 'Vernier caliper'), ('micrometer', 'Micrometer'), ('spherometer', 'Spherometer'), ('travelling', 'Travelling microscope'), ('balance', 'Balance'), ('stopwatch', 'Stopwatch'), ('thermometer', 'Thermometer')], help_text='For Measuring Instruments: choose the instrument page where this block belongs.', max_length=30),
        ),
    ]
