# Generated by Django 5.2.17 on 2026-09-17 14:49

import django.core.validators
import django.db.models.deletion
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_alter_lessonblock_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mcq', 'MCQ'), ('structured', 'Structured'), ('essay', 'Essay')], max_length=12)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2100)])),
                ('paper', models.CharField(help_text='For example: GCE A/L Physics Paper I, Tamil medium', max_length=120)),
                ('number', models.CharField(help_text='Original question number, including subpart if applicable', max_length=30)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ta', models.CharField(max_length=200)),
                ('prompt_en', models.TextField(blank=True)),
                ('prompt_ta', models.TextField(blank=True)),
                ('question_pdf', models.FileField(blank=True, upload_to='exam/questions/', validators=[django.core.validators.FileExtensionValidator(['pdf']), learning.models.validate_exam_pdf])),
                ('source_url', models.URLField(blank=True, help_text='Official source or original paper link')),
                ('marks', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('minutes', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('options_en', models.TextField(blank=True, help_text='MCQ: one option per line, matching Tamil order')),
                ('options_ta', models.TextField(blank=True)),
                ('correct_option', models.PositiveSmallIntegerField(blank=True, help_text='MCQ correct option, starting at 1', null=True)),
                ('solution_en', models.TextField(blank=True)),
                ('solution_ta', models.TextField(blank=True)),
                ('marking_pdf', models.FileField(blank=True, upload_to='exam/marking/', validators=[django.core.validators.FileExtensionValidator(['pdf']), learning.models.validate_exam_pdf])),
                ('published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_questions', to='learning.chapter')),
            ],
            options={
                'ordering': ['-year', 'paper', 'number', 'id'],
            },
        ),
    ]
