# Generated by Django 5.2.17 on 2026-09-17 16:08

import django.core.validators
import django.db.models.deletion
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_examquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['position', '-year', 'paper', 'number', 'id']},
        ),
        migrations.AddField(
            model_name='examquestion',
            name='accepted_options',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of accepted MCQ option numbers, e.g. [3, 5]. Leave empty for a single correct option.'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='import_key',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_image',
            field=models.FileField(blank=True, upload_to='exam/images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), learning.models.validate_exam_image]),
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title_en', models.CharField(max_length=200)),
                ('title_ta', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sections', to='learning.chapter')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='learning.examsection'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_exam_section'),
        ),
    ]
