# Generated by Django 5.2.17 on 2026-09-21 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_examsection_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='structured_parts',
            field=models.JSONField(blank=True, default=list, help_text='Ordered subquestions: id, prompt {en,ta}, answer {en,ta}, optional image and image_alt {en,ta}.'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
