# Generated by Django 5.2.17 on 2026-09-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_examquestion_structured_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='activity',
            field=models.CharField(blank=True, choices=[('', 'None'), ('units', 'Unit converter'), ('vernier', 'Vernier calliper'), ('uncertainty', 'Repeated measurements'), ('vectors', 'Vector components'), ('pendulum', 'Pendulum investigation'), ('particles', 'Ideal gas particles'), ('angles', 'Angle ratios'), ('dimension-builder', 'Dimension builder'), ('dimension-equations', 'Equation detective'), ('dimension-scaling', 'Pendulum scaling'), ('dimension-conversion', 'SI-CGS dimension converter'), ('error-target', 'Bias and scatter'), ('error-relative', 'Relative uncertainty'), ('error-propagation', 'Uncertainty propagation'), ('vernier-3d', '3D vernier caliper lab'), ('micrometer-3d', '3D micrometer lab'), ('spherometer-3d', '3D spherometer lab'), ('travelling-3d', '3D travelling microscope lab'), ('velocity-journey', 'Velocity: journey studio'), ('velocity-circle', 'Velocity: circular motion'), ('velocity-acceleration', 'Velocity: acceleration and gravity')], max_length=30),
        ),
    ]
